### PR TITLE
fixed validation schema for the alumni page PC input

### LINKED ISSUE #222: Update Validation Schema for Pledge Class Year
In the [BAAA Mailing List Signup form](https://github.com/mst-ka/mst-ka-site/blob/main/components/Subpages/Alumni/MailingListSignUp.js), update the validation schema to insure a user cannot enter a pledge class year that is greater than or less than 4 characters.

### PR DESCRIPTION
**Pull request by ChristianMato**
closed #222 

input no longer accepts integers less than 1903 (chapter inception) or greater than the current year

### CODE REVIEW

File: components/Subpages/Alumni/MailingListSignUp.js [hunk 1]
```diff
@@ -14,13 +14,17 @@ import { push, ref } from "firebase/database";
 import database from "../../../firebase-init.js";
 import ArrowRightIcon from "@mui/icons-material/ArrowRight";
 
+const maxDate = new Date().getFullYear()
+const minDate = 1903
```
Comment (jaredwhanisch) [inline components/Subpages/Alumni/MailingListSignUp.js:18]: nit: Can you update these variable names to be a bit more descriptive, i.e. `maxPledgeClassYear` & `minPledgeClassYear`. 

Also these statements should end in semicolons. Since you use vscode, look into installing [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and it will auto format your code for you and add those pesky semicolons automatically.

**Review by jaredwhanisch — CHANGES_REQUESTED** [review]

**Review by jaredwhanisch — APPROVED** [review]
LGTM
